#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="proyectonet")]
public partial class DataPersonaLinqDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertt_tipo_usuario(t_tipo_usuario instance);
  partial void Updatet_tipo_usuario(t_tipo_usuario instance);
  partial void Deletet_tipo_usuario(t_tipo_usuario instance);
  partial void Insertt_usuario(t_usuario instance);
  partial void Updatet_usuario(t_usuario instance);
  partial void Deletet_usuario(t_usuario instance);
  #endregion
	
	public DataPersonaLinqDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["proyectonetConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataPersonaLinqDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataPersonaLinqDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataPersonaLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataPersonaLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<t_tipo_usuario> t_tipo_usuarios
	{
		get
		{
			return this.GetTable<t_tipo_usuario>();
		}
	}
	
	public System.Data.Linq.Table<t_usuario> t_usuarios
	{
		get
		{
			return this.GetTable<t_usuario>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_tipo_usuario")]
public partial class t_tipo_usuario : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _nombre_tipo;
	
	private EntitySet<t_usuario> _t_usuarios;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onnombre_tipoChanging(string value);
    partial void Onnombre_tipoChanged();
    #endregion
	
	public t_tipo_usuario()
	{
		this._t_usuarios = new EntitySet<t_usuario>(new Action<t_usuario>(this.attach_t_usuarios), new Action<t_usuario>(this.detach_t_usuarios));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_tipo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string nombre_tipo
	{
		get
		{
			return this._nombre_tipo;
		}
		set
		{
			if ((this._nombre_tipo != value))
			{
				this.Onnombre_tipoChanging(value);
				this.SendPropertyChanging();
				this._nombre_tipo = value;
				this.SendPropertyChanged("nombre_tipo");
				this.Onnombre_tipoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="t_tipo_usuario_t_usuario", Storage="_t_usuarios", ThisKey="id", OtherKey="tipo_usuario")]
	public EntitySet<t_usuario> t_usuarios
	{
		get
		{
			return this._t_usuarios;
		}
		set
		{
			this._t_usuarios.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_t_usuarios(t_usuario entity)
	{
		this.SendPropertyChanging();
		entity.t_tipo_usuario = this;
	}
	
	private void detach_t_usuarios(t_usuario entity)
	{
		this.SendPropertyChanging();
		entity.t_tipo_usuario = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_usuario")]
public partial class t_usuario : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _nombre_usuario;
	
	private string _password;
	
	private System.Nullable<int> _tipo_usuario;
	
	private EntityRef<t_tipo_usuario> _t_tipo_usuario;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onnombre_usuarioChanging(string value);
    partial void Onnombre_usuarioChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Ontipo_usuarioChanging(System.Nullable<int> value);
    partial void Ontipo_usuarioChanged();
    #endregion
	
	public t_usuario()
	{
		this._t_tipo_usuario = default(EntityRef<t_tipo_usuario>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_usuario", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string nombre_usuario
	{
		get
		{
			return this._nombre_usuario;
		}
		set
		{
			if ((this._nombre_usuario != value))
			{
				this.Onnombre_usuarioChanging(value);
				this.SendPropertyChanging();
				this._nombre_usuario = value;
				this.SendPropertyChanged("nombre_usuario");
				this.Onnombre_usuarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_usuario", DbType="Int")]
	public System.Nullable<int> tipo_usuario
	{
		get
		{
			return this._tipo_usuario;
		}
		set
		{
			if ((this._tipo_usuario != value))
			{
				if (this._t_tipo_usuario.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Ontipo_usuarioChanging(value);
				this.SendPropertyChanging();
				this._tipo_usuario = value;
				this.SendPropertyChanged("tipo_usuario");
				this.Ontipo_usuarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="t_tipo_usuario_t_usuario", Storage="_t_tipo_usuario", ThisKey="tipo_usuario", OtherKey="id", IsForeignKey=true)]
	public t_tipo_usuario t_tipo_usuario
	{
		get
		{
			return this._t_tipo_usuario.Entity;
		}
		set
		{
			t_tipo_usuario previousValue = this._t_tipo_usuario.Entity;
			if (((previousValue != value) 
						|| (this._t_tipo_usuario.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._t_tipo_usuario.Entity = null;
					previousValue.t_usuarios.Remove(this);
				}
				this._t_tipo_usuario.Entity = value;
				if ((value != null))
				{
					value.t_usuarios.Add(this);
					this._tipo_usuario = value.id;
				}
				else
				{
					this._tipo_usuario = default(Nullable<int>);
				}
				this.SendPropertyChanged("t_tipo_usuario");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
